### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#1]
https://github.com/ropensci/wishlist

* Should it be linked from the community page?

* Should it be merged with https://github.com/ropensci/webservices/wiki/ToDo (so deleting that wiki part, and keeping only "scientific" webservices?)

* I'd be in favor of making all old unconf repos read-only after copying the text of "unsolved" ideas in new issues in the wishlist. Maybe only for the most recent unconfs.

**Comment by maelle** [comment]
Any news on the potential new forum category @stefaniebutland?

**Comment by stefaniebutland** [comment]
erp, nothing yet. 

I appreciate you checking. Does it intersect with any of your priorities/deadlines beyond general roweb3?

**Comment by maelle** [comment]
Nope, no hurry, I was just reading the issue tracker as one does. :grin:

**Comment by maelle** [comment]
I'll try to make a proposal of new forum categories to streamline things.

**Comment by maelle** [comment]
Current categories
- Blog
- Use Cases
- Packages
- Questions
- Jobs
- R-universe
- Statistical Software Peer Review
- Software Peer Review
- Community
- Best Practices
- Support 
- Code of Conduct
- Package Maintenance
- Meta
- Antartic
- Feature Requests
- Bugs

Proposed new categories
- Blog
- Use Cases
- Jobs
- Package use questions
- Package Development (for questions but also tips)
- retire R-universe as Jeroen uses GitHub discussions
- Statistical Software Peer Review 
- Software Peer Review: point to GitHub like R-universe
- Wishlist (tools one would like to exist)
- General Q&A
- Meta
- Antartic

Feature Requests posts would move (bulk move, maybe improved by hand later) to Wishlist, Bugs to Package use questions, Package Maintenance to Package development, Best practices to General Q&A, Support to Package use questions, Community to General Q&A, Packages to wishlist, Questions to General Q&A.

**Comment by maelle** [comment]
And somewhere we could state in case of doubt folks can just post to General Q&A and we'd move the post if relevant.

**Comment by stefaniebutland** [comment]
That all sounds good. Thank you!

It sounds like you are able to move the content from one category to another?

**Comment by maelle** [comment]
> It sounds like you are able to move the content from one category to another?

Yes! From each post, and in bulk as well so quite straightforward.

**Comment by maelle** [comment]
Wishlist category created & wishlist repo archived.

**Comment by maelle** [comment]
Category tweaking done, will track tasks related to communicating about the forum elsewhere.
