### ISSUE TITLE
fix Dennis Irorere's author page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#100]
@maelle I see that Dennis Irorere has added `img: img/team/dennis.jpg` to his author page. See [raw](https://raw.githubusercontent.com/ropensci/roweb3/master/content/author/dennis-irorere/_index.md); [live](https://ropensci.org/author/dennis-irorere/).

Two questions:

1. Live, it appears as oval not circle. Img dimensions are 413 × 552. Does it have to be square? How to fix?
2. should the img file be at `img: img/team/dennis.jpg` or another location not in `team`?

cc @steffilazerte

**Comment by maelle** [comment]
1. It needs to be square so maybe cropped. I decided against cropping with Hugo so it has to be cropped beforehand.
2. Another folder under img might make sense indeed.

**Comment by stefaniebutland** [comment]
I can make these changes. If `img/community/filename` is too long, please suggest alternative

**Comment by maelle** [comment]
The folder name is fine 🙂

**Comment by maelle** [comment]
I think yes, and yes indeed

**Comment by stefaniebutland** [comment]
I would not include it in blog guide, and let folks discover the option if they want to have custom pic

**Comment by stefaniebutland** [comment]
Steffi you can make the final call :-)
My take is to avoid giving so many options that it's an overload. Ppl may feel obligated to specify a pic even though it's optional

**Comment by steffilazerte** [comment]
Sounds good! I'm happy to leave it out but I'll try to remember to check in the future. Do I need to do anything for this issue?

**Comment by stefaniebutland** [comment]
No. all good thanks Steffi

**Comment by maelle** [comment]
fixed this as I was looking at other roweb3 stuff
