### ISSUE TITLE
Ligature fonts on the rOpenSci website

### ISSUE THREAD

**Issue by malcolmbarrett** [ropensci/roweb3#12]
Recently, the rOpenSci website changed to ligatured FiraCode. I believe that using ligatures in this setting is not the right choice. 

Ligatures are cool but confusing to newcomers. The fact of the matter is that R does not use them; it uses characters from the keyboard. Since it's not actually R, someone less familiar with the language is going to be confused about what they are and how to make them. I realize that they copy and paste fine, but I think that in this setting, it should be clear how it connects to the software you just managed to install on your machine.

FiraCode is very pretty, but beauty should never be more important than accessibility, at least not for an organization like rOpenSci. FiraCode has a non-ligatured version, and I think it would be good to consider that, instead.

(And for the record, this is not any sort of opinion about whether you should or should not use ligatures in general... I don't even really have an opinion about that!)

**Comment by maelle** [comment]
@malcolmbarrett Thanks again for bringing this to our attention! The website uses Fira Mono now.
