### ISSUE TITLE
Blog/Technotes display

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#124]
Perhaps there could be some clarification/tweeking of the main blog page (https://ropensci.org/blog/).

- It's not clear where technotes really are, the "#tech-notes" heading under "Highlights", implies that technotes are blog posts tagged as a technote, but since they're not, they don't actually appear in the "All Posts" section below, so people may not realize they specifically have to click on the "tag".
 
- Readers need to scroll quite a bit to reach the "All Posts" section under the featured cards and highlights section.

I'm not quite sure what kind of solutions to suggest, but for the first option, I actually wouldn't mind moving technotes to blog posts that are tagged #tech-note (not sure what @stefaniebutland thinks of this!).

For the second option, perhaps the Featured Cards could be smaller (there's a fair bit of white space)? Or part of the Highlights? Perhaps the Highlights cards could also be a bit smaller (although not sure how much smaller they can go).

**Comment by stefaniebutland** [comment]
> Readers need to scroll quite a bit to reach the "All Posts" section under the featured cards and highlights section.

This is 💯 a big issue for me, even when looking on a biggish screen


> I actually wouldn't mind moving technotes to blog posts that are tagged #tech-note (not sure what @stefaniebutland thinks of this!).

If this works for the team it works for me. It's **always** been difficult to draw a clear line between blog posts and tech notes. Tech notes are far too hidden now.

**Comment by maelle** [comment]
I have no opinion regarding tech notes' being a section or a tag. If we change things we need to remember to add redirects.

**Comment by jeroen** [comment]
We also want to create a third section with posts about r-universe, so it is a good moment to rethink this.

I think it is nice to have a page like this, for people that are only interested in technotes: https://ropensci.org/technotes/ but perhaps we can accomplish that with a tag as well.

**Comment by maelle** [comment]
> I think it is nice to have a page like this, for people that are only interested in technotes: ropensci.org/technotes but perhaps we can accomplish that with a tag as well.

Yes we can accomplish that with a tag.

**Comment by steffilazerte** [comment]
> Originally, the reason for introducing technotes was to have a quick outlet for publishing short package updates and technical things, without going through the entire review and editorial process required for official blog posts. 

I'm not sure this is how things work now. Generally speaking I assume technotes to be shorter and more technical (haha), but I give it roughly the same review process...

**Comment by maelle** [comment]
I suppose the question is, can staff members bypass reviews for their tech notes? I guess so (although I prefer getting a review when possible depending on blog editors' workload)?

**Comment by stefaniebutland** [comment]
> I give it roughly the same review process

@steffilazerte we discussed this in staff mtg today. We agreed that tech notes from staff do not have to be reviewed. They can publish at any time. This means they should also tweet their own tech note. For tech notes from community members 🤔 you can use your judgement.

Maëlle will tweak some things for tech notes e.g. marked by #technote tag

**Comment by stefaniebutland** [comment]
From Karthik:
![image](https://user-images.githubusercontent.com/11927811/106187007-e82a4500-6159-11eb-8317-5803c209d80c.png

**Comment by maelle** [comment]
Also #131 

I will also in a second time move all tech notes to the blog with a tech-note tag.

**Comment by maelle** [comment]
@steffilazerte @stefaniebutland reg Karthik's suggestion above, now that all tech notes will be blog posts.

If the featured card on the right is the latest tech note, is the featured card on the left the latest blog post?

**Comment by maelle** [comment]
I think it might be better if we kept these two featured cards the latest featured posts? Posts that can be either blog posts or tech notes. What do you think?

**Comment by stefaniebutland** [comment]
> better if we kept these two featured cards the latest featured posts? Posts that can be either blog posts or tech notes.

I agree
