### ISSUE TITLE
Project pages

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#130]
* In menu about have projects and from there both stat peer review @mpadge and r-universe @jeroen.
* Stat peer review page exists, a few tweaks
    * add blog-typed list of relevant blog posts (what tag?)
    * also add two featured cards for ???
    * add Mark
* Build R universe page. Some sort of text, list of posts tagged r-universe. Cards?

**Comment by mpadge** [comment]
> add blog-typed list of relevant blog posts (what tag?)

Tag is `statistical-software`, because full `statistical-software-review` would be too long.

> also add two featured cards for ???

Nothing yet in place to be able to add, but it will come in due course. @maelle Don't keep this issue open waiting for that - I'll definitely follow that up with you when we get that far.
