### ISSUE TITLE
behavior of talks page icons for slides and video

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#142]
On [talks page](https://ropensci.org/talks/), slides link for "Mejores paquetes de R, mejor ciencia" appears but is broken because there is [text instead of url](https://raw.githubusercontent.com/ropensci/roweb3/master/content/events/2019-01-25-conectar.md). Add slides link, or comment out resources?

related question about behavior of the icons for slides and video @maelle: For [Jeroen's rstudio talk, there's video but no slides](https://raw.githubusercontent.com/ropensci/roweb3/master/content/events/2021-01-21-rstudio-jeroen.md). The slides icon still shows, and links to the [talks page](https://ropensci.org/talks/). 

But it works when there are slides but no video. Only slides icon shows.

**Comment by maelle** [comment]
Good catch, thanks for the precise report!
