### ISSUE TITLE
commenting disabled on posts

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#144]
@sckott @maelle any chance this has something to do with changes to have posts automatically added to discourse and that now we have to manually "list" those in discourse?

`Continue Discussion` button appeared on [comm calls post](https://ropensci.org/blog/2021/02/02/ropensci-community-calls/) only after I commented in [the discourse topic](https://discuss.ropensci.org/t/ropensci-how-ropensci-runs-community-calls/2333/3). 

no discussion button on [targets](https://ropensci.org/technotes/2021/02/03/targets/) post despite it being ["listed" in discourse](https://discuss.ropensci.org/t/ropensci-targets-democratizing-reproducible-analysis-pipelines/2334)

**Comment by sckott** [comment]
I unchecked this setting, which I wasn't aware of. I think this should fix the problem where we had to mark each discourse post as "listed" manually

<img width="551" alt="Screen Shot 2021-02-04 at 5 28 31 PM" src="https://user-images.githubusercontent.com/577668/106977299-eab70c80-670e-11eb-8a2b-193b843ff3bc.png">


but i've no idea why the chat isn't enabled on the bottom of our blog posts

**Comment by sckott** [comment]
no difference in the discourse html on pages that work and those that don't

blagh, apparently deleting the comment on the discourse post that is made when we click `make listed` made the "Start Discussion" show up for this post https://ropensci.org/technotes/2021/02/03/targets/ - i guess we go through manually and undo the comments we made on posts when we clicked `make listed`

**Comment by stefaniebutland** [comment]
ok. doing some manual now
