### ISSUE TITLE
New twitter messes with the GH logo image display in the twitter card

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#15]
Tweet from Bob Rudis https://twitter.com/hrbrmstr/status/1155104691182694401

Implementation of twitter cards closed issue https://github.com/ropensci/roweb2/issues/290

**Comment by maelle** [comment]
I won't fix (well unless someone disagrees):

* not a priority,
* right now I don't even get an image if I look for tweets with the URL,
* for individual repos one can still use https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/.
