### ISSUE TITLE
Link to package docs in use cases table

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#151]
Would it be possible to link to the package docs in the [use cases table](https://ropensci.org/usecases/)? Since the docs are always docs.ropensci.org/resource, this should be pretty straightforward?

**Comment by maelle** [comment]
I'd need to tweak the code generated the use case JSON, it'd work. I'd check whether the resource is listed in rOpenSci's packages.json and add an URL if it is the case (the check is needed as some use cases might use old packages / some guide).

**Comment by steffilazerte** [comment]
Great start! Good point about several resources, comma separated seems easiest, but I hadn't thought about other resources.
