### ISSUE TITLE
Add a redirect for the volunteer form.

### ISSUE THREAD

**Issue by noamross** [ropensci/roweb3#166]
So that we have an easier to remember and recognize link to our volunteer form, could we make a simple redirect page at a URL like https://ropensci.org/software-review/volunteer that then sends the user to https://airtable.com/shrnfDI2S9uuyxtDw ?

Alternately we could actually have the page and embed the form: https://airtable.com/shrnfDI2S9uuyxtDw/embed

**Comment by maelle** [comment]
We have ropensci.org/onboarding, doesn't the embed look a bit weird btw?

**Comment by maelle** [comment]
The embedded form is really not good since after filling it the text is at the top so one needs to scroll up. I will set up a redirect instead.
