### ISSUE TITLE
add zoom link to and event

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#173]
Now that some of our events will be on zoom, such as labelathons, can an Event's `deets` act like a Comm Call `deets` to show zoom details when user clicks "Join the event/call"?

Challenge? I don't want it to interfere with non-rOpenSci events where `deets` shows "Practical information" heading. IMO that info, like a link to an R-Ladies meetup, could go outside the YAML in free text.

See this draft PR for Apr 29 Labelathon: [PR](https://github.com/ropensci/roweb3/pull/172); [Preview](https://deploy-preview-172--ropensci.netlify.app/events/labelathon01/)

Can it say "Join the event"? not "Join the call"? If it's cleaner, both comm calls and other events could say "Join the event".

![image](https://user-images.githubusercontent.com/11927811/113372196-f133c000-931c-11eb-8d14-3d0e904cb0fb.png)

**Comment by maelle** [comment]
Comm call https://deploy-preview-172--ropensci.netlify.app/commcalls/may2021-r-universe/
Event with zoom https://deploy-preview-172--ropensci.netlify.app/events/labelathon01/
Event without zoom but some other deets https://deploy-preview-172--ropensci.netlify.app/events/2021-07-05-user2021/
Is it ok?

**Comment by stefaniebutland** [comment]
> Comm call deploy-preview-172--ropensci.netlify.app/commcalls/may2021-r-universe

✅ perfect thank you

> Event with zoom deploy-preview-172--ropensci.netlify.app/events/labelathon01

I would prefer this zoom mtg code info not be displayed, other than from "join the event". The comm call display is ideal for an event with zoom. Is it possible for "Practical information" heading and `deets` content to *not* be displayed for *any* event (with or without zoom)? 
- (please please tell me if something is not wise for future use cases, or if it's time consuming to do)

![Screen Shot 2021-04-02 at 10 08 35 AM](https://user-images.githubusercontent.com/11927811/113437396-66de7100-939b-11eb-9a25-44557f2420d9.png)

> Event without zoom but some other deets deploy-preview-172--ropensci.netlify.app/events/2021-07-05-user2021

✅  Aha - when I saw "join the event" I was wondering what it would say here. Good solution.

![Screen Shot 2021-04-02 at 10 21 15 AM](https://user-images.githubusercontent.com/11927811/113438313-2c75d380-939d-11eb-839b-67fb29612099.png)


Question
- Can `deets` ever be empty?

**Comment by maelle** [comment]
* I removed practical information.
* I added the registration info to deets of the labelathon. For events I removed the default text with no RSVP needed.
* Yes deets can be empty.

Happy to implement any further feedback.

**Comment by stefaniebutland** [comment]
Thank you. Looks great
