### ISSUE TITLE
did rweekly_live tweets pick up r-universe comm call?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#174]
I don't see a tweet from Rweekly-live from me publishing the R-universe comm call, but I did see a tweet within < 30mins from when I updated the already-published Set up your pkg comm call

**Comment by maelle** [comment]
In the index.md of the R-universe comm call publishDate is set to 2021-04-06 which is the reason why, I think, R Weekly hasn't picked it up yet. Let's have a look at this again in a few days once April the 6th is in the past.

**Comment by maelle** [comment]
All good https://twitter.com/rweekly_live/status/1379222907419832320

But you need to update the description field ("some text") :grin:

**Comment by stefaniebutland** [comment]
d'oh!! I forgot I had a future (now present) date!
At least it got you to notice my description error. Thank you
