### ISSUE TITLE
pages for the rOpenSci maintained CRAN task views

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#18]

**Comment by maelle** [comment]
Which CRAN task views are actively maintained by rOpenSci, actually?

## Active
https://github.com/ropensci/Hydrology
https://github.com/ropensci/webservices (@sckott isn't it hard to keep track of all packages interfacing APIs? should the task view be limited to tools like HTTP clients, packages for data parsing)

## To be archived?

@sckott 
https://github.com/ropensci/opendata
https://github.com/ropensci/PackageDevelopment

**Comment by sckott** [comment]
I haven't been involved in opendata or PackageDevelopment, but they both haven't seen activity for a long time, and they aren't actually on cran despite those links, so probably time to archihve

**Comment by sckott** [comment]
yeah, not able to track all api pkgs. i have been removing some pkgs from the task view. i'll remove some more soon

**Comment by maelle** [comment]
https://github.com/ropensci/opendata/issues/281

**Comment by maelle** [comment]
https://github.com/ropensci/PackageDevelopment/issues/new

**Comment by maelle** [comment]
Now I think the only "rOpenSci-maintained" CRAN Task View is the hydrology one. @stefaniebutland do you think it should have a page on the website?

Note to self: if it gets a page, make sure it's indexed for internal search.

**Comment by stefaniebutland** [comment]
imo a single task view doesn't warrant a page on the site.
