### ISSUE TITLE
Share by email button?

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#181]
Blog posts have share with twitter and linkedin, but no share by email.

It's easy to copy and paste a link in email, but of the the shareable options, email is arguably the most generic. 

A share by email button could open an email with a link to the blog post and a placeholder subject and message body, so all you have to do is add the address and modify the message if you want. It's only a bit faster than just copying the link, but similar to the Twitter shortcut, and a bit more generic.

**Comment by maelle** [comment]
Such a great feature request, I am now wondering why we didn't think of this sooner! Thank you!
