### ISSUE TITLE
Resources for comm call

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#186]
@stefaniebutland 

Files examples

* [wateRinfo contributing guide](https://github.com/ropensci/wateRinfo/blob/master/.github/CONTRIBUTING.md)
* [skimr contributing guide, section about scope](https://github.com/ropensci/skimr/blob/master/.github/CONTRIBUTING.md#understanding-the-scope-of-skimr)
* [rOpenSci default code of conduct](https://github.com/ropensci/.github/blob/master/CODE_OF_CONDUCT.md)
* [ggplot2 governance file](https://github.com/tidyverse/ggplot2/blob/master/GOVERNANCE.md)
* [tidyverse default support file](https://github.com/tidyverse/.github/blob/master/SUPPORT.md)
* [cpp11 README section with a badge to a forum](https://github.com/r-lib/cpp11#getting-help-)
* [blogdown interface for new issues](https://github.com/rstudio/blogdown/issues/new/choose), [source](https://github.com/rstudio/blogdown/tree/master/.github/ISSUE_TEMPLATE)

GitHub docs
* [default community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
* [saving replies for your account](https://docs.github.com/en/github/writing-on-github/using-saved-replies)
* [configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Communication examples

* [Example of a comment about style in a PR (blogdown)](https://github.com/rstudio/blogdown/pull/432#pullrequestreview-368391904)
* [Example of a nice no in an issue (pkgdown)](https://github.com/r-lib/pkgdown/issues/1396#issuecomment-695848545)

Others 
* [pkgdown (dev version) for customizing what's in the sidebar and footer](https://pkgdown.r-lib.org/dev/articles/customization.html#layout)
* [tidyverse style guide](https://style.tidyverse.org/)

**Comment by stefaniebutland** [comment]
Thank you @maelle !! I will add these to comm call page

**Comment by maelle** [comment]
Also, not featured in my talk (I'm resisting adding them because of the time limit), but recent tweets of @jimhester's are insightful & very useful (why is there no hashtag for them :stuck_out_tongue_winking_eye:)

https://twitter.com/jimhester_/status/1359584159317000195
https://twitter.com/jimhester_/status/1357680037470875649
https://twitter.com/jimhester_/status/1356272709345419264
https://twitter.com/jimhester_/status/1355195248612356099
https://twitter.com/jimhester_/status/1351930803656257544
