### ISSUE TITLE
Feed of "help wanted" issues

### ISSUE THREAD

**Issue by noamross** [ropensci/roweb3#192]
In order to maximize the visibility of "help wanted" labels in rOpenSci packages and promote cross-support within the community, I think it would be helpful to have a process that consumes the feed of rOpenSci and rOpenSciLabs issues, filtering to only those that are tagged "help wanted" (and "help-wanted"), and

- Generates a page of recent help wanted issues (perhaps a column at https://ropensci.org/packages/).
- Feeds a Slack channel with alerts (#help-wanted-issues)
- Runs a twitterbot (@ropensci_help ?)
- Creates summaries suitable for a newsletter section ("Recent help requests")

**Comment by maelle** [comment]
Do we think a Twitter bot would be really useful?

**Comment by noamross** [comment]
I am honestly unsure. Perhaps @stefaniebutland has a better idea of the audience. I follow some bots of that sort and they are helpful. For RO it wouldn't be my main feed me because I'm a Slack user and would check that regularly.

**Comment by stefaniebutland** [comment]
Glad you opened this issue @noamross. 

Gut feeling is that a twitter bot might be the best way to get it "out there" for folks who want to "give back to open source", and folks who want to get more R experience or exposure by contributing to an rOpenSci project. 

But before creating bot or the Slack channel, we'd want to see that there is actually some turnover of issues being opened and closed.

@steffilazerte might have thoughts to add after our first labelathon this week (just finished a great planning/zoomroomtesting/anticipating meeting for that).

**Comment by maelle** [comment]
Thanks @stefaniebutland, but would one expect the tweets to come from a bot, or from rOpenSci account itself?

I fear a bot would get little attention, event tweets (not only fleets) are fleeting IMHO. :thinking: 

I'll wait until after the labelathon to work on anything related to this, then.

**Comment by steffilazerte** [comment]
I agree, I think tweeting is great, but maybe better if they come from rOpenSci account, especially as there probably won't be *that* many new issues each week.

Perhaps this is something I could add to my Monday workflow (usecases, featured pkgs, and blog post mentions). I could create a script to grab them, format a tweet and then manually schedule the tweet for a given day, like I do with the usecases. I don't think it would add much to my weekly work flow.

**Comment by stefaniebutland** [comment]
Yes to tweeting from main rOpenSci acct. I like your idea Steffi.

> there probably won't be that many new issues each week.
especially since labelathon folks were mostly *not* working on rOpenSci pkgs and that is fine!

Good to keep track if you can, of the ebb and flow of help wanted issues in rOpenSci pkgs

**Comment by steffilazerte** [comment]
Okay, if no objections I will add this to my Monday workflow, but that doesn't resolve the idea of a feed (which I think is great!) and which I could link to in the tweets.

**Comment by steffilazerte** [comment]
I'm working on this workflow and would love to include the package maintainer/authors twitter handle so they can see that we're tweeting their issues.

My question is, who do I tag? for a package like weathercan, it's not an issue, I'm really the only person working on it, but what about packages with more contributors?

For example, this issue was opened and tagged by one contributor, but not by the maintainer... https://github.com/ropensci/tinkr/issues/26 would I tag the contributor who opened the issue or the maintainer of the R package?

**Comment by maelle** [comment]
Maybe both the maintainer (so they'd retweet it) and the issue author?

I'm also wondering how you'd get Twitter usernames though?

**Comment by steffilazerte** [comment]
That's the thing, sometimes it's tricky. Ideally, people would have twitter handles in their github profile so I could grab that easily, but it'll probably be a semi-manual process (I don't think there will be that many issues to tweet about).

Thanks for the advice!

**Comment by steffilazerte** [comment]
I have a workflow set up in the [comms repo](https://github.com/rosadmin/comms/tree/master/content_n_programs/twitter_promo/issues)

This creates a workflow for automatically grabbing "help wanted" issues (and similar), figuring out who the package maintainer is, who labelled the issue, whether the issue is also labelled as "good first issue" or "beginner" and then creating a draft tweet.

See the README for specifics.

I'd love feedback!

**Comment by maelle** [comment]
Sorry, looking at this now, awesome work @steffilazerte! (thanks for the ping @stefaniebutland!)

* Your READMEs are always such a pleasure to read, so exhaustive!
* I like the flexibility you have in the labels searched for.
* I think it's good indeed not to use too old issues. Maybe later you could switch to "updated" after a certain date?
* Using ropensci.org/authors as one of the data sources is smart!
* I've gotten into renv at last (for one project :joy:), it could be used for saving the dependencies.
* The tweet scheduling is manual right?
* I opened a PR to add space between emojis and words, detail. :nail_care: 
* I see the code depends on an utils.R script one folder up: could this utils.R become part of a steffutils package instead?
* Will the person creating the new tweets always commit & push the new issue txt file?
