### ISSUE TITLE
Search blog posts or site?

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#195]
I've been finding myself looking for a blog search option. Is that something that could be useful, or do we want to stick to tags/author/date?

It might be nice to have a site wide search. For example, if you searched for label-athon, you would then find events, blog posts and community calls related to that.

**Comment by maelle** [comment]
Note to self: https://github.com/HaoZeke/hugo-theme-hello-friend-ng-hz to see stork in action (with stork maybe we could put more things in the search index)
