### ISSUE TITLE
More parameterizable Twitter share button

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#20]
@noamross' idea on the standup call.

Make text in tweet intent URL depend on a parameter in posts' metadata.

A fallback could be is that even without the field, it includes author handles from author data

**Comment by steffilazerte** [comment]
I was just thinking that this could be great, especially with community posts to make sure the authors get more exposure and have a twitter metric to see how their posts are being shared.

**Comment by maelle** [comment]
This is an excellent argument!
