### ISSUE TITLE
some missing avatars on author page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#201]
https://ropensci.org/author/

![Screen Shot 2021-05-10 at 4 31 57 PM](https://user-images.githubusercontent.com/11927811/117736763-416c3080-b1ad-11eb-9f1a-59c7f8cfe2a9.png)

**Comment by stefaniebutland** [comment]
@maelle

**Comment by maelle** [comment]
Good catch @stefaniebutland, thank you! I was afraid for one moment it meant the API we use for that went away, but not, it just slightly changed the query parameter format needed. I'll also fix the CSS for having _round_ avatars again.
