### ISSUE TITLE
CSS for forum header matching ropensci website is wonky

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb3#215]
ping @maelle 

![Screen Shot 2021-06-07 at 8 47 31 AM](https://user-images.githubusercontent.com/577668/121050108-28837a80-c76d-11eb-9a4f-ff20c2295307.png)

Same in Brave and Firefox, haven't looked at others

**Comment by maelle** [comment]
was there an update of the plugin used to create it?

**Comment by sckott** [comment]
ha! there was an update avail, fixed now
