### ISSUE TITLE
fix link in 2018 blog post

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#248]
A link in this post https://ropensci.org/blog/2018/05/03/onboarding-is-work/ no longer exists. Should we just remove the link?

Text
> It appears to take our reviewers a similar amount of time to review R packages as scientists take to review a manuscript ...

Link no longer exists. Goes to home page: https://publishingresearchconsortium.com/index.php/112-prc-projects/research-reports/peer-review-in-scholarly-journals-research-report/142-peer-review-in-scholarly-journals-perspective-of-the-scholarly-community-an-international-study

search for "peer review" and "scholarly" gave no hits

**Comment by maelle** [comment]
Thanks for catching this. Recording my process in case it's useful.

From Internet Archive https://web.archive.org/web/20190409015510/https://publishingresearchconsortium.com/index.php/112-prc-projects/research-reports/peer-review-in-scholarly-journals-research-report/142-peer-review-in-scholarly-journals-perspective-of-the-scholarly-community-an-international-study

Thanks to the title (and authors) seen above I found https://www.stm-assoc.org/2009_10_13_MWC_STM_Report.pdf

**Comment by maelle** [comment]
(and I saw the numbers mentioned on page 26 of the PDF!)
