### ISSUE TITLE
MODIStsp doesn't show up in pkgs page search

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#251]
Searching `modis` at https://ropensci.org/packages/all/ does not list MODIStsp

https://docs.ropensci.org/MODIStsp/

**Comment by maelle** [comment]
Could you please try again? Maybe it was just a glitch.

![image](https://user-images.githubusercontent.com/8360597/134762924-44083f3b-8c63-4895-8daf-db1f1620715a.png)

**Comment by stefaniebutland** [comment]
Works now thanks
