### ISSUE TITLE
make quotes in posts prettier 

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#262]
The default formatting of quotes in posts makes them not-obvious and the font-size relative to regular text looks strange (this is not a criticism of our fine web site maintaining peeps!). 

Example: https://ropensci.org/blog/2021/10/12/editors2021/

Something like [the quote here](https://contributing.ropensci.org/intro.html) is a bit better but I'm not wedded to a particular style

**Comment by stefaniebutland** [comment]
- a colored background;
  - maybe not. would have to be very very subtle like the grey on white in the bs4_book

Thinking add `"` sign and making the vertical side bar and `"` both either blue or grey and no change in text size (since that would be same as bs4_book

**Comment by maelle** [comment]
For my own reference https://getbootstrap.com/docs/4.0/content/typography/#blockquotes

**Comment by stefaniebutland** [comment]
> do you also encounter the case where you need to add a source for a quote?

yes the contrib guide example is one - person's name + link out to origin if online
