### ISSUE TITLE
How to subscribe to events

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#263]
Asked by @Bisaloo (thank you!).

> Is there a public rOpenSci calendar one can subscribe to? And then every new event would automatically be added to your calendar. This would also be useful for community members that are not very active on social media.

**Comment by Bisaloo** [comment]
I'm using thunderbird. I find it convenient to have it at the same place as my emails.

**Comment by maelle** [comment]
Ok, good to know. I am having trouble getting it to sync on Google calendar but I'm investigating.

**Comment by maelle** [comment]
I'll look at my own calendar to see when I see the updates.

@stefaniebutland can you subscribe to https://deploy-preview-266--ropensci.netlify.app/events/index.ics just to confirm you see the correct time slots for the next coworking events? To be sure I didn't mess up with timezones.

**Comment by Bisaloo** [comment]
> @Bisaloo has this event moved to the 13th of February?

Yes! Everything seems to be working perfectly! :smile:

**Comment by maelle** [comment]
The event was updated in my calendar! Yay, less than one hour delay! (and yay for obsessive refreshing). So that makes .ics in Google Calendar acceptable I think.

**Comment by Bisaloo** [comment]
Not a solution but it looks like you're not alone: https://support.google.com/calendar/thread/95111555/opening-an-ics-file-opens-and-closes-a-continuous-looping-tab-in-google-chrome?hl=en

**Comment by Bisaloo** [comment]
My wild guess would be that your mac is set up to open `.ics` files with google chrome. So it tries to open it in chrome, which thinks that you want to download this file and open it, so it opens in chrome again, etc. 

If this is indeed the cause of the issue, this might help: https://apple.stackexchange.com/questions/3509/can-i-set-os-x-to-automatically-open-ics-files-in-ical

**Comment by maelle** [comment]
Thanks @Bisaloo!

@stefaniebutland did this help?

We might need to add some explanation to the page itself as Chrome is so popular. Re-opening for better tracking.

**Comment by stefaniebutland** [comment]
whew! Thanks @Bisaloo it worked!

**Comment by stefaniebutland** [comment]
my update to the solution here https://apple.stackexchange.com/questions/3509/can-i-set-os-x-to-automatically-open-ics-files-in-ical

is to set .ics to open in `Calendar.app`, since iCal is the old name

re: adding explanation - it would be helpful but would make the explanatory text too long. where could it go?

**Comment by maelle** [comment]
Ok, opened a PR.
