### ISSUE TITLE
Improve styling of tables

### ISSUE THREAD

**Issue by jeroen** [ropensci/roweb3#27]
The packages table on https://ropensci.org/blog/2020/05/19/covid-19-open-data/ looks pretty bad. It only shows a small part of the table and it isn't obvious that it is scrollable? 

In the old site we displayed the full table: https://roweb2.netlify.app/blog/2020/05/19/covid-19-open-data/

Bootstrap 4 (which we use) has many built-in options to style tables: https://getbootstrap.com/docs/4.0/content/tables/

**Comment by maelle** [comment]
you mean not wide enough?

**Comment by jeroen** [comment]
It only shows a small part of the table and it isn't obvious that it is scrollable? 

In the old site we displayed the full table: https://roweb2.netlify.app/blog/2020/05/19/covid-19-open-data/

**Comment by maelle** [comment]
I think the easiest solution is to add shortcodes for tables.

**Comment by maelle** [comment]
* Adding a shortcode that allows us to use any class on the table (on the table only though, not on the table header for instance) is easy.
* However our CSS does not have the bootstrap rules on tables which I do not understand yet.

Exploration
* Our main.scss imports boostrap scss https://github.com/ropensci-org/roweb3-styles/blob/a9af4e006de19cadbd9a519b0360ff7a6d1533ec/scss/main.scss#L7
* And boostrap scss itself imports the table scss.

**Comment by maelle** [comment]
Hmm actually we have the table CSS. table-dark works but looks horrible. table-striped needs some HTML tweaks in the rows too...

**Comment by maelle** [comment]
We'll need to refactor the CSS a bit to apply current rules on tables (defined by the designer/developer) apply only on tables that are not of the class table.

**Comment by maelle** [comment]
https://github.com/ropensci/roweb3/pull/35

https://github.com/ropensci-org/roweb3-styles/pull/2 (So we use Boostrap as a base for the CSS but then we want our table rules to apply only on non Boostrap tables so I added `not(.table)` everywhere...)

**Comment by maelle** [comment]
Opinions @jeroen? (no hurry, except by a few weeks I will have forgotten all details :wink:)
