### ISSUE TITLE
Forward onboading link for reviewers to the form

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#277]
Forward https://ropensci.org/onboarding/ to https://airtable.com/shrnfDI2S9uuyxtDw. Right now the original link is referenced throughout the 2020 newsletters and was (until https://github.com/ropensci-org/contributing-guidance/issues/67) referenced by the contributing guide

**Comment by maelle** [comment]
Excellent point, thank you @steffilazerte!
