### ISSUE TITLE
Fix building of pagination.min.js

### ISSUE THREAD

**Issue by jeroen** [ropensci/roweb3#30]
Go to https://ropensci.org/packages/all/ and on the bottom click `next`, nothing happens. 
The console says: `Uncaught ReferenceError: new_page is not defined`

**Comment by maelle** [comment]
I switched from pagination.min.js to pagination.js again, which seems to have fixed it.

It means

* I hadn't checked things properly, sorry, and thanks for catching this.
* The npm build script we have doesn't update pagination.min.js properly from pagination.js. I'd like to fix that eventually, but for now we're ok with the not minified script I think.

**Comment by maelle** [comment]
So, I think the problem is that JS minification also shortens variable names. So what should be minified is the main script and "pagination" script _together_.

However, I think it's fine to use a not minified version of the pagination/search script.
