### ISSUE TITLE
"new" post does not point to newest post

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#31]
At https://ropensci.org/

![Screen Shot 2020-10-01 at 9 23 55 AM](https://user-images.githubusercontent.com/11927811/94837273-e9747c80-03c8-11eb-8ce3-e4482e8e5acc.png)

**Comment by stefaniebutland** [comment]
will "new!" point to the most recent blog post OR tech note? (hoping yes)

**Comment by stefaniebutland** [comment]
ah...I see in [README](https://github.com/ropensci/roweb3/blob/master/README.md)
> the featured post or tech note at the top of the homepage is the latest featured one.

Could "new!" be the most recent blog post? I propose this because if most recent post is not "featured" then it's much less visible than in the past when it used to be first visible thing on blog page

**Comment by mpadge** [comment]
> Most recent blog post or most recent post (so tech note or blog post)?

I don't care as long as I'm there!! I'm sure my moment of glory here will only last a couple of days, so I'd like to bask in it if possible. Please

**Comment by stefaniebutland** [comment]
I got yer back @mpadge. You're featured on home page and blog page now
![Screen Shot 2020-10-01 at 10 56 47 AM](https://user-images.githubusercontent.com/11927811/94845637-d1a2f580-03d4-11eb-801a-8e8cee2e3a3e.png)


![Screen Shot 2020-10-01 at 10 56 08 AM](https://user-images.githubusercontent.com/11927811/94845566-b932db00-03d4-11eb-9069-02030d048163.png)

**Comment by stefaniebutland** [comment]
most recent post (so tech note or blog post)

**Comment by maelle** [comment]
Done! Sorry Mark for the problems you get as "new website guinea pig"!

**Comment by mpadge** [comment]
all good! you are amazing @maelle - so many different issues on so many disparate things, and you keep on fixing them all regardless. I am more than slightly in awe here :rocket:

**Comment by maelle** [comment]
Guess who created the problem in the first place, though :joy:
