### ISSUE TITLE
integration of posts with discourse broken

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#33]
Does integration need to be updated? No link from post to forum, even for Mark's roweb3 post

![Screen Shot 2020-10-01 at 4 13 21 PM](https://user-images.githubusercontent.com/11927811/94872346-40964380-0401-11eb-93cd-da7a49f95469.png)

**Comment by sckott** [comment]
we know. not been able to find a solution yet

**Comment by mpadge** [comment]
I've been seeing nothing but that for what feels like most of this year, so it's definitely a long-standing issue
