### ISSUE TITLE
Issues on the 'Help Wanted' page are sorted alphabetically by 'Date Opened' column.

### ISSUE THREAD

**Issue by salix-d** [ropensci/roweb3#346]
Hi,

I just noticed that the way the table on the 'Help Wanted' page sorts the dates is alphabetical and not chronological, meaning all issues opened in April of any years appear first. I'd suggest changing the format to YYYY-MM-DD so it can be sorted chronologically.
 
https://github.com/ropensci/roweb3/blob/main/themes/ropensci/layouts/help-wanted/list.html
I think changing line 59 from `<td>{{ dateFormat "January 2, 2006" .opened }} </td>` to `<td>{{ dateFormat "2006-01-02" .opened }} </td>` should fix it.

**Comment by maelle** [comment]
Thanks a ton @salix-d!
