### ISSUE TITLE
Add Champions Program project

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#382]
We can use the same scheme as the review project.  The first section will be:

General information about the program
Benefit
TimeLine

Then we will add: who to apply.

After the application close, we will add a section with:

- Our Champions (like our team in the other sections)
- Our Mentors (like our team in the other sections)

**Comment by maelle** [comment]
Something to decide (later): will champions and mentors also appear on the team page.

**Comment by yabellini** [comment]
I imagine the mentors and the champions listed on the webpage.

**Comment by maelle** [comment]
on the about page you mean? in my mockup they are already on the champions page itself.

**Comment by yabellini** [comment]
I understand your question now; you mean like the fellows on the about page, right?  I saw the mockup page, and that is what I imagined.

**Comment by maelle** [comment]
yes, should there be under the team, like fellows are currently on ropensci.org/about

**Comment by yabellini** [comment]
The call for mentors is still missing from the webpage. I'm creating that content.
