### ISSUE TITLE
Resource page's commcalls link is a 404

### ISSUE THREAD

**Issue by mustberuss** [ropensci/roweb3#384]
https://github.com/ropensci/roweb3/blob/1f31f83f5cd22bf991034dac9871bb757ac203f6/data/resources/resources.json#L40

Hi, 

I got a 404 when I clicked on the "Community Call Archive" link on the resources page.  Please update to https://ropensci.org/commcalls/ when you get a chance.

I am very new to R and my localhost is not yet smart enough to help me :smiley:  
Thank you

**Comment by maelle** [comment]
Thank you!! Fixed in https://github.com/ropensci/roweb3/commit/4ba1b0829afb478104682179760750c657993a49
