### ISSUE TITLE
Layout for "2 months in 2 minutes"?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#4]
Something to keep in mind for the redesign, we might want special layouts for such posts.

The layout name would be indicated in posts' frontmatter. https://gohugo.io/templates/lookup-order/

**Comment by maelle** [comment]
@stefaniebutland should we discuss this, when is the next "2 months in 2 minutes" post scheduled?

**Comment by stefaniebutland** [comment]
Not yet. 

Update: In the new year, Scott will be moving to monthly newsletter. Along with the possibility of Steffi turning annual report metrics into an internal monthly thing, I'd like to explore with Scott and Steffi how much we (they) can increase newsletter automation paired with some 2month 2min (moving to -> 3 months in 3 mins) automation.

**Comment by stefaniebutland** [comment]
@maelle ok to close this now since news will be on blog?

**Comment by maelle** [comment]
Good catch!
