### ISSUE TITLE
Author folder missing for Janani Ravi

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#41]
It's there in [roweb2](https://github.com/ropensci/roweb2/tree/master/content/author/janani-ravi) but not [roweb3](https://github.com/ropensci/roweb3/tree/master/content/author/janani-ravi) 

and website shows partial presence of the content https://ropensci.org/author/janani-ravi/

**Comment by maelle** [comment]
I forgot to add it when I updated roweb3 with roweb2 content, sorry!
