### ISSUE TITLE
Add information about Call for Mentors on Champions Webpage

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#415]
We need a way to add the call for mentors information on the webpage about the Champion Program.  Perhaps as Resources linking to the blog post?

What do you think @maelle ?

**Comment by maelle** [comment]
Could you also tweak the text of the page to link to the info for mentors earlier on the page? 
Your edit suggestions to the resources sound good but I think it'd be nice for the info to also be in the main text.
