### ISSUE TITLE
Support Mastodon info

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#425]
- [x] In author profiles
- [x] Listing rOpenSci's one if we start using it regularly (cc @yabellini)
- [x] On team page

**Comment by yabellini** [comment]
See where we should add the link on the webpage to mastodon verify us: https://mastodon.social/@emilyriederer/109293694036325026

_You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your Mastodon profile. The link back must have a rel="me" attribute. The text content of the link does not matter. Here is an example_

<a rel="me" href="https://fosstodon.org/@ropensci">Mastodon</a>

**Comment by yabellini** [comment]
There Is some discussion on NUMFocus Slack and they said fosstodon will review this policy.

So I will said we can do this, and if allow Spanish take too long we can move the account to another server.

**Comment by maelle** [comment]
@yabellini I added the link following the instructions, now I'm not sure how you trigger the verification, maybe edit the profile settings in Mastodon to be sure Mastodon crawls the page again?

**Comment by maelle** [comment]
@yabellini on my own Mastodon profile to force verification I had to change the name of the field with my website to "home", which I guess was the way the crawling was triggered.

**Comment by yabellini** [comment]
Done!
![imagen](https://user-images.githubusercontent.com/2473676/201652261-07b84ec3-7017-43d8-9724-5b41be0452c2.png)

**Comment by maelle** [comment]
yay!!
