### ISSUE TITLE
Using alert-info box for linking among posts

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#443]
@maelle, we'd like to use the alert-info box formating when linking among blog posts (for when we're cross-posting or linking to a post in a different language).

We often use quotes, but they're not quite right. We found an [older post](https://ropensci.org/blog/2017/04/11/assertr/) that we like. We applied that to the R-universe interviews post ([preview](https://deploy-preview-406--ropensci.netlify.app/blog/2022/11/22/r-universe-stars-1-en/)) which looks good.

**Question**
Right now this is pure HTML:

```
<div class="alert alert-info" role="alert">
<a href="/blog/2022/11/22/r-universe-stars-1-en/" target="_blank">See the English version of this blog post</a>
</div>
```

Anyway it could be a shortcode or something similar so we could use markdown? No problem if not!

**Comment by steffilazerte** [comment]
Also pinging @yabellini to be in the know :grin:

**Comment by maelle** [comment]
Yes! I had forgotten too. One should use the `preface` YAML field. Example in https://github.com/ropensci/roweb3/blob/main/content/blog/2022-11-23-r-universe-stars-1-es/index.md
Where in https://blogguide.ropensci.org/ should I document this?

**Comment by steffilazerte** [comment]
Awesome! I created an issue in the blog guide. If you get to it great, but I'm also happy to make it happen!
