### ISSUE TITLE
change sorting of Events

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#45]
See [current example](https://ropensci.org/events/) with Oct22 event listed before Oct 8. I feel like that order should be reversed

![Screen Shot 2020-10-05 at 3 58 57 PM](https://user-images.githubusercontent.com/11927811/95140421-b6f9b500-0723-11eb-9e9e-1752a34cfedb.png)

**Comment by maelle** [comment]
oops, thank you!!
