### ISSUE TITLE
Use katex to include math?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#473]
@jeroen this is related to https://github.com/ropensci/roweb3/pull/459#issuecomment-1384344282

I've experimented and the following works however I'd like your advice.

**Solution 1 with {katex}**

- in the Rmd file, using katex for instance

````markdown
I will consider the following true data generating process (DGP):

```{r results='asis'}
string <- "\\begin{aligned}
x_t & \\sim N(-0.5 y_{t-1} + x_{t-1} + z_{t-1}, 0.3^2)\\\\
y_t & \\sim N(0.7x_{t-1}, 0.3^2)\\\\
\\end{aligned}"
katex::katex_html(string)
```

for `r katex::katex_html("t=2, \\ldots, 100", displayMode = FALSE)`, where the
````
- in the YAML for the post, adding `katex: true`
- in our partial for the head, adding

```html
{{ if .Params.katex }}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css" integrity="sha384-vKruj+a13U8yHIkAyGgK1J3ArTLzrFGBbBc0tDp4ad/EyewESeXE/Iv67Aj8gKZ0" crossorigin="anonymous">
           {{ end }}
```

it looks ok

![image](https://user-images.githubusercontent.com/8360597/213673673-50b8a556-e1cd-4049-8f2a-2ddf401f4a9c.png)

We'll get math rarely I think. If we go with this solution, I'll change the R Markdown myself (adding all the katex calls, doubling all backslashes).
We could call the YAML parameter "math" instead of "katex".

**Solution 2: using katex JS directly?**

Instead of re-writing all the LaTeX maybe when the katex/math parameter is TRUE, we should load not only katex stylesheet but also the JS.
Con: I have no idea how it'd look in feedreaders, especially on R Bloggers (not sure it's that big of a deal as people could click through to the actual blog).

**Comment by jeroen** [comment]
I think solution 1 is good. I don't think you need `results='asis'`, the examples in the [katex vignette](https://github.com/ropensci/katex/blob/master/vignettes/katex-tests.Rmd) do not have this either.

If you don't want to make any changes to the template you can even use `insert_css = TRUE` like below and that will work with the current template sort of like a widget (but is perhaps less elegant)


````markdown
```{r}
string <- "\\begin{aligned}
x_t & \\sim N(-0.5 y_{t-1} + x_{t-1} + z_{t-1}, 0.3^2)\\\\
y_t & \\sim N(0.7x_{t-1}, 0.3^2)\\\\
\\end{aligned}"
katex::katex_html(string, include_css = TRUE)
```
````

**Comment by maelle** [comment]
Thank you @jeroen!
