### ISSUE TITLE
Paragraph on r-universe blog post

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#493]
The English version of the first interview about r-universe (https://ropensci.org/blog/2022/11/23/r-universe-stars-1-en/) now has a paragraph at the beginning that says this is a series of tech notes about r-universe.

Something to take into account: the interviews with r-universe users are a series on their own, and there are no tech notes. 

If we want to keep that text on the interviews blog post, then we need to add the same text to the Spanish and French versions of the post and to the next one.

**Comment by maelle** [comment]
@jeroen should we change the tag used for the alert appearance then?

**Comment by jeroen** [comment]
I like having a little r-universe intro text there, also for the interview posts. Shall I modify the wording of the blob to not say 'technote' but more generally introduce r-universe?
