### ISSUE TITLE
Font sizes on mobile dont match full width version

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb3#50]
https://ropensci.org/blog/2020/10/06/hacktober2020/

On mobile

![image](https://user-images.githubusercontent.com/138494/95377427-673bfa80-0897-11eb-911f-67b0f6d6effe.png)

On wider widths the font sizes are the same. So something is off in the responsive css.

**Comment by maelle** [comment]
Indeed, there was no responsive rule for ul (and no rule for ol, which I added).
