### ISSUE TITLE
Make code of conduct page bilingual like the blog posts

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#509]

**Comment by maelle** [comment]
I can't remember what I meant here, given the Spanish COC lives at https://ropensci.org/es/codigo-de-conducta/ as expected.

**Comment by yabellini** [comment]
Perhaps it has to do with no list the CoC in the English nav-bar?  and have a Español tag on the CoC like the one we have on blog post?

**Comment by maelle** [comment]
Good point! But as long as we don't have more static pages translated, I prefer to leave the navbar as is.
