### ISSUE TITLE
update packages text on homepage

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#51]
![Screen Shot 2020-10-07 at 4 09 56 PM](https://user-images.githubusercontent.com/11927811/95397274-a5e1ad00-08b7-11eb-993e-585d8cbb4443.png)

**Comment by maelle** [comment]
to?

**Comment by stefaniebutland** [comment]
That text from original roweb2 designer focusing on document formats seems odd.  

Are one of these hybrids from https://ropensci.org/packages/ plus part of above ok?

Use our carefully vetted, staff- and community-contributed R packages to acquire data from both your own and from public sources, analyze it, visualize it, and add your narrative. Combine our tools with the rich ecosystem of R packages. 

Use our carefully vetted, staff- and community-contributed R software tools that lower barriers to working with local and remote scientific data sources. Combine our tools with the rich ecosystem of R packages.

**Comment by maelle** [comment]
Yes, thank you!!
