### ISSUE TITLE
CRAN's <doi:...> tags are parsed as links

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/roweb3#56]
`<doi:...>` tags are now explicitly encouraged by CRAN for each new submission. E.g. from UL:

> Is there some reference about the method you can add in
the Description field in the form Authors (year) \<doi:.....\>?

But in the new package registry on rOpenSci's website, these tags are parsed as simple links. This means `<doi:10.21105/joss.01857>` will lead to the non-existing page http://doi:10.21105/joss.01857.

You can see an example of this in the package lightr.

PS: I don't know if this issue belongs in this repo. Feel free to move it if necessary

**Comment by maelle** [comment]
Thanks a ton @Bisaloo!

**Comment by Bisaloo** [comment]
FYI, there are also some other similar tags (even though I'm not sure how common they are):

> Please write references in the description of the DESCRIPTION file in the form
authors (year) \<doi:...\>
authors (year) \<arXiv:...\>
authors (year, ISBN:...)
or if those are not available: authors (year) \<https:...\>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

**Comment by maelle** [comment]
@Bisaloo where is the list btw? Not https://cran.r-project.org/web/packages/policies.html?

**Comment by Bisaloo** [comment]
I don't know. This quote is from an email I got from CRAN last week.

**Comment by maelle** [comment]
ok, thanks, I'll keep this open then.

**Comment by maelle** [comment]
https://github.com/wch/r-source/blob/ecb3f045044b3cb0e6ec31fb24c559f559e1432c/src/library/tools/R/QC.R#L8425

**Comment by maelle** [comment]
sorry for the delay @Bisaloo, and thanks a lot for catching this! I see no package with arxiv info yet in the registry, but it could happen so better to handle this.
