### ISSUE TITLE
Formatting code output to be more obvious

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#62]
This may be a personal preference.

I find the current formatting of code output (output, messages, etc.) to be formatted a bit too much like the main body text. 

When there is a lot of output it's not so bad ([example](https://ropensci.org/technotes/2020/08/25/scientific-name-parsing/#namext)). However when there's only a small amount of output, like a message or similar, the output almost looks like lost text ([example](https://ropensci.org/technotes/2019/12/19/urls-tidying/#broken-internal-urls)).

I find the output especially hidden when there is little code and little output ([preview example](https://deploy-preview-57--ropensci.netlify.app/blog/2020/10/20/searching-medrxivr-and-biorxiv-preprint-data/#use-case-2--reproducible-searching-and-exporting))

In older posts, the output is included in the same code block as the source and is formatting to be more obvious. In this (example)[https://ropensci.org/technotes/2019/02/27/handlr-release/#the-r6-approach] you might imagine that with the one-line text between the code blocks that if the output were formatted as it is in newer posts, they might start to blend together. 

Would it be possible to add a background colour or change the text colour or something similar to the output to emphasize what it is?

**Comment by maelle** [comment]
What if we added a box around all code including code output?

![image](https://user-images.githubusercontent.com/8360597/97865509-9c0e6680-1d0a-11eb-9b4d-53ed12efb867.png)

cc @jeroen

**Comment by maelle** [comment]
:wave: @jeroen @steffilazerte

**Comment by steffilazerte** [comment]
I think that would help a lot
