### ISSUE TITLE
Changing markup for cross-posted blog posts

### ISSUE THREAD

**Issue by mfenner** [ropensci/roweb3#643]
Content on the rOpenSci blog is frequently cross-posted elsewhere. The rOpenSci blog recently started registering DOIs for blog posts with relevant metadata. Adding a link to the cross-posted content to the DOI metadata would be good practice and would make it easier to discover the cross-posted content.

The DOIs are registered via the [Rogue Scholar](https://rogue-scholar.org) service and the metadata and content are captured via the rOpenSci JSON Feed at https://ropensci.org/blog/index.json. Cross-posted content in newer blog posts is highlighted at the beginning of the content using an alert box and the language `This is cross-posted on ...`, for example in https://ropensci.org/blog/2023/08/01/r-universe-and-cran/. This information is not included in the JSON Feed and therefore can't be included in DOI metadata.

I propose a generic solution that also works for other blogging platforms besides Hugo, which need to address the same issue:

* Add a new section (separated by HTML tag h2, h3 or h4) at the end of the post called `Acknowledgments`. Other names for this section are of course also possible, but ideally the same name is used consistently.
*  In this section use exactly the same content as now, the sententence `This is cross-posted on ...` with a link (or links) to other places where this content is posted. The link can also be a DOI if the cross-posted content has one, e.g. because the blog post was also posted to Zenodo.
* Markup to highlight this content e.g. as alert is optional.
* I would suggest that this replaces the current solution, but the alert box at the beginning of the post could of course remain.

An example blog post using this approach and linking to cross-posted content is https://doi.org/10.53731/ewrv712-2k7rx6d.

**Comment by maelle** [comment]
Note to self: https://www.jsonfeed.org/version/1/#extensions-a-name-extensions-a

**Comment by maelle** [comment]
fixed in #652
