### ISSUE TITLE
Cross-posting merges with Preface... does this matter?

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#670]
@yabellini, @maelle 

For example, this code https://github.com/ropensci/roweb3/blob/412f70c6889e0dd7cb6f23c37a19052629ebc708/content/blog/2017-12-01-unconf-welcome.md?plain=1#L6-L13

results in this

[![image](https://github.com/ropensci/roweb3/assets/14676081/ae4a3f62-0325-4ec6-9e60-9c7eeb7ffe03)](https://ropensci.org/blog/2017/07/18/value-of-welcome/)

Do we want to add a bit of breathing room, or is it okay as is?

Also, perhaps the cross-post key "name" should read "the Trellis blog as part of a series of reflections the Fellows are sharing" and then the final sentence of the preface should be removed?

**Comment by maelle** [comment]
> Do we want to add a bit of breathing room, or is it okay as is?

Yes, good point!

> Also, perhaps the cross-post key "name" should read "the Trellis blog as part of a series of reflections the Fellows are sharing" and then the final sentence of the preface should be removed?

That'd be more involved since the current template allows for only one URL per cross-post so I'll leave it as is.

Thank you!
