### ISSUE TITLE
labelling staff maintained packages

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#69]
Figure out how packages should be labelled staff-maintained or not at https://ropensci.org/packages/all/ when e.g. most of Mark's packages were developed prior to rOpenSci employment and might be maintained on his own time

**Comment by sckott** [comment]
we discussed in 2020-11-05 staff meeting that we'd discuss this at the upcoming policy meeting before the end of the year  - ping @maelle @noamross

**Comment by maelle** [comment]
now solved!

Only Scott's and Jeroen's packages count as staff-maintained by default.

For others cc @mpadge @steffilazerte to make a package count as staff-maintained it needs to have a line `.ropensci-staff` in .Rbuildignore.
