### ISSUE TITLE
Updating Multilingual Project

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#697]
- Add the Translation of the Spanish dev guide as a resource. This is the final link for the guide in spanish? https://devdevguide.netlify.app/es/preface.es.html
- Link to the GitHub Project of the Portuguese translation as a resource (so people can contribute to the project). 
- Change the role to reviewers instead of translator for Pedro, Elio and Pao.

**Comment by maelle** [comment]
it's not the final link as we'll release devguide.ropensci.org at some point, but it's the link for now :smile_cat:
