### ISSUE TITLE
Pull request redirection on blog post

### ISSUE THREAD

**Issue by Rekyt** [ropensci/roweb3#716]
As I read the great blogpost by @maelle and noted a small typo and [suggested to correct it](#715), I clicked on the "Open a pull request" link on the side of the article, which is great to directly go to the good URL.

The link was: https://github.com/ropensci/roweb3/tree/HEAD/content/blog/2024-01-16-deepl-update-babeldown/index.Rmd
but GitHub redirected me towards: https://github.com/ropensci/roweb3/blob/946064549df121fc99b05134278ed8ca18c9af43/content/blog/2024-01-16-deepl-update-babeldown/index.Rmd
which was not on the `main` branch so I couldn't edit a suggestion right away (I had to manually select the `main` branch)

I don't fully understand GitHub links and the differences between trees and blobs, but replacing the `tree` in the first URL by `blob` redirected me directly to the actual up-to-date file:
 https://github.com/ropensci/roweb3/blob/HEAD/content/blog/2024-01-16-deepl-update-babeldown/index.Rmd
 
So probably replacing `tree` by `blob` would work, but I don't know enough about GitHub and redirection to make sure it doesn't break anything.
This is the block of code that provides the links: https://github.com/ropensci/roweb3/blob/946064549df121fc99b05134278ed8ca18c9af43/themes/ropensci/layouts/partials/blogs/blog-single.html#L89
and this is the structure computing the link: https://github.com/ropensci/roweb3/blob/946064549df121fc99b05134278ed8ca18c9af43/themes/ropensci/layouts/partials/edit-link/edit-link.html

**Comment by maelle** [comment]
Thank you!! I must say I just switch from master to HEAD when we changed the default branch name, which wasn't the smartest thing.
