### ISSUE TITLE
Broken post author name on archive page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb3#74]
On blog Archive page https://ropensci.org/archive/ there's a list of numbers instead of author name. Author page looks ok & link from blog post works: https://ropensci.org/author/liam-brierley/

![Screen Shot 2020-11-10 at 8 56 15 PM](https://user-images.githubusercontent.com/11927811/98770533-52232180-2397-11eb-9a7c-cbb2d4e777b7.png)

**Comment by maelle** [comment]
Good catch!

It's because the author field was

```
author: Foo Bar
```

Instead of

```
author:
  - Foo Bar
```

Now, the theme should be flexible so I fixed the layout. I just wanted to explain why it happened for that post and not others. :-)
