### ISSUE TITLE
Merge software review and statistical review pages

### ISSUE THREAD

**Issue by noamross** [ropensci/roweb3#756]
The https://ropensci.org/software-review/ page doesn't show all editors, I think the statistical editors are left off.

**Comment by yabellini** [comment]
Because they are listed here: https://ropensci.org/stat-software-review/

**Comment by noamross** [comment]
Then we should probably merge the two pages and re-write the text.  This is a bit vestigial from back when we envisioned having wholly separate review processes, but they've since mostly merged into one.  Self-assigning.

**Comment by maelle** [comment]
@noamross @mpadge happy to help if needed

**Comment by mpadge** [comment]
The way I see it, the main decision on our side would be what to do with the current text-heavy description of the *Statistical Software Review* project. My suggestion would be removing list of categories there, and reducing all that text to a single paragraph. The rest of the merge should then be relatively straightfoward. @noamross Do you agree?

**Comment by maelle** [comment]
removing/condensing text is what we did for the R-universe page :grin:

**Comment by yabellini** [comment]
Thanks, @maelle, for working on this!  I need the new version of this page so I can advance with the Spanish translation of static pages on our website (more urgent now with the projects in Spanish).
