### ISSUE TITLE
remove anchors from RSS feed

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#80]
they come from the render hook https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks

**Comment by maelle** [comment]
@jeroen I was looking at GitHub READMEs for inspiration, and they also have the anchor in the HTML at all times. So I'm not sure we could solve this via CSS. Maybe I'll look another time :thinking:

**Comment by jeroen** [comment]
OK thanks. It already looks better on r-bloggers with the smaller icons: https://www.r-bloggers.com/2020/11/moving-away-from-travis-ci/

**Comment by maelle** [comment]
It could only look better :joy: :see_no_evil:

**Comment by maelle** [comment]
bootstrap has classes special for print display, now I wish we could just add classes for R-bloggers display :thinking:

**Comment by jeroen** [comment]
I think the bootstrap class is equivalent of doing `"style: display:none;"

**Comment by maelle** [comment]
yeah but we want to do that only for rbloggers

**Comment by jeroen** [comment]
For the rss feed you mean? I don't think any rss feed should contain anchor icons, not just r-bloggers?

**Comment by maelle** [comment]
I think we don't have the issue with other feeds, at least not so much, because they use the summary rather than the whole content.

**Comment by maelle** [comment]
https://github.com/gohugoio/hugo/issues/7160

**Comment by jeroen** [comment]
The huge anchors also show up in our forum, if you click "show full post": https://discuss.ropensci.org/t/ropensci-behind-the-magick-updates-to-imagemagick-and-beyond/2329

**Comment by maelle** [comment]
Oops, this is not good indeed. @sckott how does this integration work? Could the link to full post direct to the website instead?
I am wondering where best to tweak this.

**Comment by maelle** [comment]
Also say we publish a post on the website, it gets re-posted on the forum, we update the post on the forum: does it get updated in the forum?

**Comment by sckott** [comment]
Here's the plugin for the integration https://github.com/discourse/discourse-chat-integration I don't see any way to change anything about the integration. I'm guessing most people don't read the post in the forum, but maybe they do

**Comment by maelle** [comment]
Thanks @sckott 

@jeroen I'll try your idea to make the anchor an icon.
