### ISSUE TITLE
Author profile doesn't display picture

### ISSUE THREAD

**Issue by yabellini** [ropensci/roweb3#825]
Cagri's profile doesn't display his picture: https://ropensci.org/author/alican-cagri-gokcek/ , but the file exists. @maelle, probably you will capture why it is not working.  🙏

**Comment by maelle** [comment]
When I read the sentence " @maelle, probably you will capture why it is not working. " I thought I'd feel like a failure if I didn't find the bug, successful manipulation @yabellini :joy:
