### ISSUE TITLE
Event as coworking, but shouldn't be?

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roweb3#843]
Hi @yabellini, just checking in, but I think that Liz's event shouldn't have the coworking key, right? Or is it a special session?

https://github.com/ropensci/roweb3/blob/c1d2fb3cae5355e09f3106fb3f79c68f473d5663/content/events/2024-09-10-rsr-learn-and-use.md?plain=1#L10

**Comment by yabellini** [comment]
It is champions program webinar. No coworking and no comm call.

**Comment by yabellini** [comment]
I need the event have the add to calendar + link to join to zoom as a comm call or co-working session (I don't know if the key have anything to do with those two thing, mention that just in case)

**Comment by steffilazerte** [comment]
Hmm, @maelle, thoughts?

**Comment by maelle** [comment]
The deets field works for any event: https://github.com/ropensci/roweb3/blob/81649838d22d9743886d80764d3bd0334fd96a6d/themes/ropensci/layouts/events/single.html#L16 (I didn't know off-hand, I went and checked)

**Comment by maelle** [comment]
The website has been re-built by Netlify, the details are still here (I had checked locally before pushing :innocent: ):

![image](https://github.com/user-attachments/assets/299e4173-8e33-4905-a472-1b1507cc8fa7)

**Comment by steffilazerte** [comment]
Thanks @maelle!

**Comment by yabellini** [comment]
Awesome! 🙏
