### ISSUE TITLE
Rogue Scholar DOI not working for "Deposits In The Wild" blog post

### ISSUE THREAD

**Issue by collinschwantes** [ropensci/roweb3#856]
The DOI issued for this blog post does not appear to resolve properly.

Here is the rogue scholar page: https://rogue-scholar.org/posts/10.59350/zdmg9-ryp97

Here is the DOI: https://doi.org/10.59350/zdmg9-ryp97

**Comment by maelle** [comment]
@mfenner did anything recently change in the API output? Thank you!

**Comment by maelle** [comment]
In https://api.rogue-scholar.org/blogs/ropensci I do see the post, I'm trying to figure out whether maybe the problem is that URL is not a character field.

**Comment by mfenner** [comment]
The DOI is properly registered now, after re-registering the blog post. I assume the issue was caused by recent major infrastructure work by Crossref, but I will keep an eye on this.

**Comment by maelle** [comment]
https://ropensci.org/blog/2024/08/06/git-tricks/ is the latest post for which there is a DOI. Something is broken after that.

**Comment by maelle** [comment]
Thanks so much @mfenner for fixing!

Thanks so much @collinschwantes for reporting!
