### ISSUE TITLE
Broken link in software-review page

### ISSUE THREAD

**Issue by LizHareDogs** [ropensci/roweb3#858]
Hi! THis website is an amazing resource!

I noticed a broken link in /content/software-review/_index.md.

It's on line 7, and it's the link for [reviewers] that's supposed to link to the dev_guide. It gives me a 404 error (https://devguide.ropensci.org/softwarereviewintro.html#reviewers)/

I didn't do a PR because I wasn't sure if it was supposed to refer to chapter 7 (https://devguide.ropensci.org/softwarereview_reviewer.html) in general or something else specifically.

**Comment by maelle** [comment]
Thank you!!
