### ISSUE TITLE
Solve typo

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/roweb3#879]
Hi 👋 
Thanks for publishing the blogpost [How to cite R and R packages](https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/). I found it very interesting. I would like to let you know about a typo in line 79:
https://github.com/ropensci/roweb3/blob/2a9edacec93cecc09959f41d50cfaea57b258831/content/blog/2021-11-16-how-to-cite-r-and-r-packages/index.Rmd#L79

"by the by the" ➡️ "by the".

**Comment by maelle** [comment]
Thank you so much @damianooldoni!!

**Comment by maelle** [comment]
https://github.com/ropensci/roweb3/commit/aac47fabc66121eb3c76648b9445dbe6f836bbfa
